---
abstract: 'A Module::Install extension that allows the user to interactively specify custom installation directories'
author:
  - 'David Coppit <david@coppit.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Module::Install::CustomInstallationPath
name: Module-Install-CustomInstallationPath
no_index:
  directory:
    - inc
    - t
requires:
  File::HomeDir: 0
  perl: 5.004
version: 0.1040
